### ISSUE TITLE
Tron Bike Colors

### ISSUE THREAD

**Issue by derpferd** [UMDLARS/tron#1]
Currently all Tron bikes are the same color. Each bike should be a different color.
To fix this:

- [x] Create sprites for 7 additional bike colors. (Total of 8 colors)
- [x] Create trails for 8 bike colors.
- [x] Edit game to use different colors for each bike.

**Comment by pahp** [comment]
There are now bikes and trails for five colors and the code supports it. Create a new issue if you want to support 8 bikes and I'll do that.
